collections:
    testcol:
      index:
        type: cdx
        api_url: http://localhost:8081/testcol?url={url}&closest={closest}&sort=closest
        replay_url: ""
      archive_paths: ./

enable_http_proxy: true
